# Spring properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/coronavirus
      #'mongodb+srv://admin:mongo@cluster0-51bxy.mongodb.net/coronavirus?retryWrites=true&w=majority'
# HTTP Server
#server:
#  port: 8090   # HTTP (Tomcat) port
  
   