# Spring properties
#spring:
#  data:
#    mongodb:
      #host: localhost
      #port: 27017
      #uri: mongodb://localhost/coronavirus
# HTTP Server
#server:
#  port: 8090   # HTTP (Tomcat) port
  
   